# Generated by Django 5.0.6 on 2024-07-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
